name: spotify_mockup
description: A UI Clone of Spotify.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/slander.png
    - assets/love_is_gone.png
    - assets/this_is_post_malone.jpg
    - assets/this_is_queen.jpg
    - assets/this_is_alan_walker.png
    - assets/arijit.png
    - assets/this_is_illenium.png
    - assets/favourite.jpg
    - assets/dm1.png
    - assets/dm2.png
    - assets/close.png
    - assets/placeholder_add.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
